// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Authenticate(arg1:main.Credentials):Promise<Record<string, any>>;

export function GetDeviceList(arg1:number):Promise<Array<main.PlantDevice>>;

export function GetDevicePointData(arg1:number,arg2:string,arg3:Array<number>):Promise<Array<Record<string, any>>>;

export function GetPlantList():Promise<Array<main.Plant>>;

export function GetStoredCredentials():Promise<main.Credentials>;

export function Logout():Promise<void>;

export function UpdateTrayStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateTrayTitle(arg1:string):Promise<void>;
