// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate(arg1) {
  return window['go']['main']['App']['Authenticate'](arg1);
}

export function GetDeviceList(arg1) {
  return window['go']['main']['App']['GetDeviceList'](arg1);
}

export function GetDevicePointData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDevicePointData'](arg1, arg2, arg3);
}

export function GetPlantList() {
  return window['go']['main']['App']['GetPlantList']();
}

export function GetStoredCredentials() {
  return window['go']['main']['App']['GetStoredCredentials']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function UpdateTrayStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTrayStatus'](arg1, arg2);
}

export function UpdateTrayTitle(arg1) {
  return window['go']['main']['App']['UpdateTrayTitle'](arg1);
}
